import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

const app = express();
const PORT = 3000;

app.use(express.json());

// API route: AI Drug Interaction Explanation
app.post("/api/explain", async (req, res) => {
  try {
    const { drugs, interaction } = req.body;

    if (!drugs || !Array.isArray(drugs) || drugs.length < 2) {
      return res.status(400).json({
        error: "At least two drugs are required for AI explanation."
      });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        error: "GEMINI_API_KEY is not configured on the server. Please ensure the API key is set in the environment secrets."
      });
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build"
        }
      }
    });

    const prompt = `
You are a pharmacology educator explaining a drug interaction to pharmacy and healthcare students.

Medications Involved: ${drugs.join(" + ")}
Severity Level: ${interaction?.severity || "Unknown"}
Interaction Type: ${interaction?.interaction_type || "Unknown"}
Summary: ${interaction?.educational_summary || interaction?.mechanism || "No specific mechanism details available"}
Mechanism: ${interaction?.mechanism || "N/A"}
Clinical Significance: ${interaction?.clinical_significance || "N/A"}
Possible Effects: ${Array.isArray(interaction?.possible_effects) ? interaction.possible_effects.join(", ") : interaction?.possible_effects || "N/A"}
Monitoring: ${Array.isArray(interaction?.monitoring) ? interaction.monitoring.join(", ") : interaction?.monitoring || "N/A"}
Management: ${Array.isArray(interaction?.management_considerations) ? interaction.management_considerations.join(", ") : interaction?.management_considerations || "N/A"}

Please provide a structured, student-friendly explanation based PRIMARY on the verified clinical facts provided above. Do not invent unverified clinical facts.

Respond strictly in JSON format with the following fields:
1. "simpleExplanation": A 2-3 sentence overview in easy-to-understand student language.
2. "whyItHappens": Explanation of the underlying physiological or pharmacological mechanism (e.g. enzyme inhibition, receptor competition, additive effects).
3. "clinicalImportance": Why pharmacists and healthcare professionals must care about this specific interaction.
4. "hypotheticalExample": A simple, safe educational case scenario illustrating how this might present clinically (e.g. "A 65-year-old taking Drug A is prescribed Drug B and experiences...").
5. "keyPoint": One concise, memorable takeaway bullet point for exam prep or clinical practice.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        temperature: 0.3,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            simpleExplanation: { type: Type.STRING },
            whyItHappens: { type: Type.STRING },
            clinicalImportance: { type: Type.STRING },
            hypotheticalExample: { type: Type.STRING },
            keyPoint: { type: Type.STRING }
          },
          required: ["simpleExplanation", "whyItHappens", "clinicalImportance", "hypotheticalExample", "keyPoint"]
        }
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response generated by AI model.");
    }

    const parsed = JSON.parse(text);
    return res.json({ success: true, explanation: parsed });

  } catch (error: any) {
    console.error("Error in /api/explain:", error);
    return res.status(500).json({
      error: error.message || "Failed to generate AI explanation."
    });
  }
});

// Health check route
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa"
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`PharmaCheck AI server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
